### ISSUE TITLE
how to enable glowing effect for active tabs

### ISSUE THREAD

**Issue by stove-jeebs** [andreasgrafen/cascade#104]
the left-most tab is currently open
![image](https://github.com/andreasgrafen/cascade/assets/67490238/108c9eeb-5e7f-4011-84ec-26e747396617)

**Comment by stove-jeebs** [comment]
yep

**Comment by andreasgrafen** [comment]
well.. the active tab *should* be darker than the non active ones to differentiate it. weird that this isn't happening on your setup.
![image](https://github.com/andreasgrafen/cascade/assets/35840154/d9f52984-4364-4244-a920-8846dff68784)

The coloured lines aren't the active tab, but [Container Tabs](https://support.mozilla.org/en-US/kb/containers) which is a different feature.
