### ISSUE TITLE
Using Tree Style Tabs with this theme

### ISSUE THREAD

**Issue by archziac** [andreasgrafen/cascade#105]
Is there a way i can use tree style tabs properly with this theme? if there isnt then can this please be implemented?

**Comment by andreasgrafen** [comment]
There currently is no TST integration, and I personally do not plan on adding one any time soon as I'm not using TST and have no idea how to approach styling it accordingly. There is #78 which also addresses TST support and maybe someone will be able to pick up the work that has been done for it.
