### ISSUE TITLE
Active tabs have bigger box & refresh icon not centered vertically

### ISSUE THREAD

**Issue by Dyzean** [andreasgrafen/cascade#13]
![image psd](https://user-images.githubusercontent.com/69681505/144741345-9a8d00af-46de-42f6-89b9-4b4aa6ad9b93.png)

as the title says, the active tab box/background have bigger size compared to the normal one and the search icon is not centered vertically.

System Info:
OS: Arch Linux
Firefox Version: 94.0.2

**Comment by Dyzean** [comment]
actually almost all icon are not centered vertically
here's a screenshot on normal mode.
![image](https://user-images.githubusercontent.com/69681505/144741418-22bfafe0-8f81-407a-b706-45eca6ccb37a.png)

**Comment by andreasgrafen** [comment]
hmm.. Interesting. I don't have any issues with that on my setup.
I'll go through a few different setups later, in hope that I can reproduce these issues to fix them eventually.

Are you maybe using Firefox in Compact mode?
This might cause issues as some values had to be hardcoded in the CSS.

**Comment by Dyzean** [comment]
> 

nope im not using compact mode

**Comment by benyaminl** [comment]
> hmm.. Interesting. I don't have any issues with that on my setup. I'll go through a few different setups later, in hope that I can reproduce these issues to fix them eventually.
> 
> Are you maybe using Firefox in Compact mode? This might cause issues as some values had to be hardcoded in the CSS.

The answer is simple, just hardcode the URL bar height then all will be solved. I test i on my cascade on nightly.

**Comment by andreasgrafen** [comment]
While I'm sure that this would fix the issue.. I'd still prefer it to work the other way around with everything falling in line like intended without forcing values. And as this isn't an overall issue this might break it for other people.

**Comment by andreasgrafen** [comment]
I'll close this for now as I can't find a proper solution, but the forced way seems to do the trick. I have this on my list to possibly fix in a later update.

**Comment by teahwiz** [comment]
waterfall fixes this

**Comment by Dyzean** [comment]
Yea just tested waterfall it works fine for some reason

**Comment by andreasgrafen** [comment]
Oh, okay! That's a great point actually. Based on that I'd assume that the buttons actually influence the height of the URL- and Tabbar. Other than that I don't see any changes in Waterfall that would fix this behaviour. Sadly that still means that for a version without buttons it would be necessary to set a fixed value for the height as far as I can tell.

**Comment by andreasgrafen** [comment]
**Update:** This is not officially fixed! [Line 116](https://github.com/andreasgrafen/cascade/blob/a16181ec77da1872f102e51bcf2739c627b03a1b/userChrome.css#L116) seems to be the root of this behaviour. I've edited the margin value, which in return makes the bar space properly. This is, more or less, a hardcoded height value like it was proposed before, but at least it's working by default now!
