### ISSUE TITLE
Windows 7 Aero Fix For Cascade

### ISSUE THREAD

**Issue by Rajbir98** [andreasgrafen/cascade#14]
![image](https://user-images.githubusercontent.com/84771149/146779628-8913e1fb-9188-42b0-b9ae-3a6c864140f0.png)

**Comment by Rajbir98** [comment]
![image](https://user-images.githubusercontent.com/84771149/146779757-8e73a29e-e903-476a-8b1f-1faebd8da2ad.png)

**Comment by Rajbir98** [comment]
this is without cascade

**Comment by Rajbir98** [comment]
I have tried a little to fix but I still have a problem
![image](https://user-images.githubusercontent.com/84771149/146781561-4de5a9b4-c396-429b-995c-8940fbd8c6c7.png)

**Comment by Rajbir98** [comment]
how could i make the rest of all transparent

**Comment by andreasgrafen** [comment]
It should work out if you remove the background colour definitions for the URLbar and Toolbars or set them to transparent.
You can most likely even use the same modified version mentioned in #10 [comment](https://github.com/andreasgrafen/cascade/issues/10#issuecomment-968290051).
