### ISSUE TITLE
The selected label is not distinguished by color bars 

### ISSUE THREAD

**Issue by R0FGV** [andreasgrafen/cascade#15]
![图片](https://user-images.githubusercontent.com/19688305/147382029-9329df15-0bcc-436d-bee9-f6c8e5afa51d.png)
The selected label is not distinguished by color bars

**Comment by andreasgrafen** [comment]
Could you please elaborate on what you mean by "selected label"? I'm not quite sure what you're talking about. :/

**Comment by R0FGV** [comment]
> Could you please elaborate on what you mean by "selected label"? I'm not quite sure what you're talking about. :/

Sorry for not expressing clearly. I mean I have opened a lot of webpages, but at the top I can't distinguish which webpage I am staying on, under the dark theme.
I did not show the green indicator bar for distinguishing such as the introduction picture 
![图片](https://user-images.githubusercontent.com/19688305/147395248-382a4b31-3b6b-49ed-ad79-12b7f63dd961.png)

**Comment by andreasgrafen** [comment]
Ooh, I see! These colour bars are [Container Tabs](https://addons.mozilla.org/en/firefox/addon/multi-account-containers/). 
You can use them to seperate certain things like cookies depending on the container you're opening the site in. It's a simplified way to use mutliple Profiles.

They don't mark your current tab, but mark the specific container that tab is opened in. Your active tab should be highlighted by a darker shade of grey. If the contrast isn't high enough you can change secondary colour on [line 52](https://github.com/andreasgrafen/cascade/blob/main/userChrome.css#L52).

**Comment by R0FGV** [comment]
> Ooh, I see! These colour bars are [Container Tabs](https://addons.mozilla.org/en/firefox/addon/multi-account-containers/). You can use them to seperate certain things like cookies depending on the container you're opening the site in. It's a simplified way to use mutliple Profiles.
> 
> They don't mark your current tab, but mark the specific container that tab is opened in. Your active tab should be highlighted by a darker shade of grey. If the contrast isn't high enough you can change secondary colour on [line 52](https://github.com/andreasgrafen/cascade/blob/main/userChrome.css#L52).

i got it, thank u~
