### ISSUE TITLE
The hightlighted Tabs doesnt have the top line and a bit bigger than others

### ISSUE THREAD

**Issue by SwiftyPop** [andreasgrafen/cascade#16]
I see that mine look pretty different than the screenshot in README.![6L9bEeEz0G](https://user-images.githubusercontent.com/90952326/147805139-f6ccde55-84fa-4025-9943-cd2267d3c28d.gif)

Isn't it supposed to look like this?:
![librewolf_MAbh4VbUiM](https://user-images.githubusercontent.com/90952326/147805249-912e6d2f-3f9b-4ec7-9e65-90e7ad7db300.png)
How can I fixed this?

I'm in Windows 10

**Comment by andreasgrafen** [comment]
This behaviour was also discussed in #13. It's not intentional, but I can't find a way to reproduce this on Mac or Linux, but I don't have a Windows device on hand. The proposed solution (for now, and maybe the best way to handle this) would be to set the URL bar height in the CSS.
