### ISSUE TITLE
Selection colour when selecting multiple tabs

### ISSUE THREAD

**Issue by k-andzhanovskii** [andreasgrafen/cascade#17]
![Screenshot 2022-01-09 at 10 02 10@2x](https://user-images.githubusercontent.com/54621335/148677919-2bd6f05f-e9a7-406c-99d1-e584700e2eb5.png)

Is there a way to change this colour?

**Comment by andreasgrafen** [comment]
Today I learned: You can select multiple tabs in Firefox. How did I miss that feature?

Anyway.. this seems to do the trick of making all selected tabs the correct colour:
`#tabbrowser-tabs:not([noshadowfortests]) .tabbrowser-tab:is([visuallyselected=true], [multiselected]) > .tab-stack > .tab-background:-moz-lwtheme { background: var(--uc-hover-colour) !important; }`

**Comment by k-andzhanovskii** [comment]
I think the native support for multiple tab selection was introduced relatively recently, maybe just a few years ago. I found out about it only a few months ago, but use it everyday now 🙂

Your code worked like a charm, thanks a lot!
