### ISSUE TITLE
Hide the Go button

### ISSUE THREAD

**Issue by k-andzhanovskii** [andreasgrafen/cascade#18]
![Screenshot 2022-01-09 at 10 19 17@2x](https://user-images.githubusercontent.com/54621335/148678286-f0fcd05b-5c67-4920-9c24-ec3038004eb1.png)

Trying to hide the Go button but the following code doesn't work for some reason:

```
urlbar-go-button { 
    display: none !important;
}
```

Please could you advise?

**Comment by andreasgrafen** [comment]
If you have it in your CSS exactly like you have pasted it here you're just missing the ID selector `#`.
`#urlbar-go-button { display: none !important; }` works perfectly fine for me.

That's a good catch tho, thanks! I've totally missed that button, and I'll remove that one with the next release as well. c:

**Comment by k-andzhanovskii** [comment]
Ah right, silly me!

Thanks for pointing this out, looking forward to the next release 🙂

**Comment by andreasgrafen** [comment]
No worries; if I were to get a penny every time I messed something up like this I would have been rich by now. :D
