### ISSUE TITLE
Accent colour in about:addons and about:preferences

### ISSUE THREAD

**Issue by k-andzhanovskii** [andreasgrafen/cascade#19]
<img width="1500" alt="Screenshot 2022-01-09 at 10 33 20@2x" src="https://user-images.githubusercontent.com/54621335/148694941-6ebc6cb8-b833-449e-8e7a-ad30c9fef717.png">

<img width="1255" alt="Screenshot 2022-01-09 at 18 12 07@2x" src="https://user-images.githubusercontent.com/54621335/148694921-a801d388-8f84-4876-b9a2-48240e2310d9.png">

Is it possible to change this colour via CSS?

**Comment by andreasgrafen** [comment]
Uhm, yes. I've seen this be done before. I don't recall how tho, but it's something to place in the userContent file, I believe. You might find a solution over on [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS) or in [MrOtherGuy's FFCSS hacks](https://github.com/MrOtherGuy/firefox-csshacks/) repo. c:
