### ISSUE TITLE
Commenting out colors leads to graphical bug (transparency)

### ISSUE THREAD

**Issue by jacksongoode** [andreasgrafen/cascade#21]
If a user comments out the block suggested in userChrome.css the browers title bar will appear transparent and glitchy (Fedora 35). It seems that defaults are not assumed for the theme variables if they are commented out.

**Comment by jacksongoode** [comment]
It might be good to set a [fallback](https://developer.mozilla.org/en-US/docs/Web/CSS/var()#custom_properties_with_fallbacks_for_use_when_the_property_has_not_been_set) somewhere that uses the vars within the colours block.

**Comment by andreasgrafen** [comment]
oh shoot! I completely forgot to answer this!
I'll def. look into that further. Simply inheriting the default value doesn't seem to work for some reason. :c

**Comment by andreasgrafen** [comment]
Okay, so.. from what I can tell inheriting default values is a little tricky because of the way these variables are implemented in the default browser.css. But i think i've found a way to get around this. Would you mind giving this a spin to see if it works for you too?
