### ISSUE TITLE
error during installation of the xpi: not verified component.

### ISSUE THREAD

**Issue by fabiorug** [andreasgrafen/cascade#29]
nightly win seven 16022022

**Comment by andreasgrafen** [comment]
Hi, do you have the [experimental settings](https://github.com/andreasgrafen/cascade/pull/23#issuecomment-1020846205) enabled in your browser?

_»On developer edition and nightly, you can install it by enabling extensions.experiments.enabled and disabling xpinstall.signatures.required«_
