### ISSUE TITLE
URL suggestion box has black text, its illegible

### ISSUE THREAD

**Issue by TripleK2004** [andreasgrafen/cascade#30]

**Comment by andreasgrafen** [comment]
You may need to switch your browsers Theme to Dark as well.
Settings > Extensions & Themes > Themes

Let me know if that helped. ^—^

**Comment by TripleK2004** [comment]
> You may need to switch your browsers Theme to Dark as well. Settings > Extensions & Themes > Themes
> 
> Let me know if that helped. ^—^

Can i disable that urlbox in anyway, i have turned off suggestions and everything else, it shows 1 line of the text being typed and the default search engine
![image](https://user-images.githubusercontent.com/76064725/158920540-6c7def0f-c228-475e-ae0a-ee23b3301bb6.png)

**Comment by andreasgrafen** [comment]
Neat, glad it helped, and yeah… it's not really compatible with the system theme or anything like pywall, but i wanna get into that, i just haven't found the time. c:
