### ISSUE TITLE
support this plugin

### ISSUE THREAD

**Issue by sankemao** [andreasgrafen/cascade#32]
i have found this plugin : 
https://addons.mozilla.org/en-GB/firefox/addon/adaptive-tab-bar-color/
and i think it will be more awsome if this theme can change tabbar color

**Comment by andreasgrafen** [comment]
> **Known Issues**
> Does not support CSS themes

I'll def. give this a shot,  but I don't really have high hopes of getting this to work as the Readme already states that it doesn't work with custom CSS. :c

**Comment by andreasgrafen** [comment]
I've played around with the plugin a little more and it's actually possible to make it work with Cascade as well. The only issue: Firefox keeps crashing consitently with the plugin enabled. I haven't checked out this bevahiour *without* Cascade, but my assumption is that it's not the custom CSS causing the issue here, but the plugin itself. So that's something to keep in mind.

**Comment by RaafatTurki** [comment]
@andreasgrafen out of curiosity what edits did you attempt, I'd like to dig more into this.
It would be great if you make an `adaptive` branch (or just throw it in `experimental`)

**Comment by andreasgrafen** [comment]
It seems to work when you just strip out all colour definitions. Tho it's glitchy from time to time.

**Comment by RaafatTurki** [comment]
Just so we're on the same page, I've stripped the colors out like so:
![image](https://user-images.githubusercontent.com/16624558/177183962-20c1b5d7-a3a4-4f18-b236-186ec10167da.png)

And now my firefox looks like my gtk theme, however there are some opacity issues that didn't exist before:
*transparent alert message*
![image](https://user-images.githubusercontent.com/16624558/177184440-eb6191c8-b0ce-4fcc-89fe-c8052ffeb723.png)
*tabs have no background hence tab names overlap when dragging*
![image](https://user-images.githubusercontent.com/16624558/177184698-f9fc8083-9acf-4a92-a072-6f39adf8716e.png)

And after installing the Adaptive Tab Bar Color extension all hell broke loose (navbar and search suggestions went full transparent)
![image](https://user-images.githubusercontent.com/16624558/177185160-f9941336-4a10-4e91-91c4-0d80ad4f5e4d.png)

On the bright side none of the crashed you've mentioned occurred to me.
I'd really appreciate some feedback here, Did I strip the colors the same way you did? Iet me know what you think.

**Comment by RaafatTurki** [comment]
Ah, That's more like it, no crashes as well, big thanks!

One thing is I've noticed the elements that get effected by the 3 main color definitions change depending on if the plugin is installed on not
```css
--window-colour:                     #1E2021;
--secondary-colour:                  #191B1C;
--inverted-colour:                   #FAFAFC;
```
I haven't looked into the other colors.

**Comment by andreasgrafen** [comment]
Oh, right! I totally forgot to check that..
You might be able to get away with removing lines [444](https://github.com/andreasgrafen/cascade/blob/8c5867d516273dded5cf1ecc5e8ede64721963c8/userChrome.css#L444) to [451](https://github.com/andreasgrafen/cascade/blob/8c5867d516273dded5cf1ecc5e8ede64721963c8/userChrome.css#L451) to fix the urlbar popout colours.

**Comment by RaafatTurki** [comment]
Actually doing that results in the same opacity issue in the last image above.

**Comment by andreasgrafen** [comment]
nyeh..
What happens if you additionally remove lines [438](https://github.com/andreasgrafen/cascade/blob/8c5867d516273dded5cf1ecc5e8ede64721963c8/userChrome.css#L438) to [441](https://github.com/andreasgrafen/cascade/blob/8c5867d516273dded5cf1ecc5e8ede64721963c8/userChrome.css#L441)?

Maybe even line [417](https://github.com/andreasgrafen/cascade/blob/8c5867d516273dded5cf1ecc5e8ede64721963c8/userChrome.css#L417).

**Comment by RaafatTurki** [comment]
Yeah that fixes it, I'm noticing a lot of pieces were removed in order to make this happen, maybe split the style sheets and let the user require the parts that fit their needs?

This would work great for colors as well since users could update cascade and keep their custom colors

**Comment by andreasgrafen** [comment]
Yeah. That's a long term plan I haven't implemented yet.. Tho, I'm currently working on a complete rewrite of Cascade anyway. So that will come for sure! c:

**Comment by andreasgrafen** [comment]
Heya … it has been quite a while but I finally got around to implement all the things I wanted into a reworked version of Cascade. If you're still interested in this you could check out the [rework branch](https://github.com/andreasgrafen/cascade/tree/rework) and just remove the [colours include](https://github.com/andreasgrafen/cascade/blob/dd148243c1629b3eb9ee46566e5d96c045f1d4f1/chrome/userChrome.css#L32) from the main file to ensure you're using the system colour. I've done some quick testing and on my end it works quite well with this plugin. c:
