### ISSUE TITLE
force colors

### ISSUE THREAD

**Issue by wael444** [andreasgrafen/cascade#33]
is it currently possible to force the cascade CSS colors? Firefox by default is light theme, so the cascade light colors apply as well.
a workaround is to have the same colors for dark and light themes.

**Comment by andreasgrafen** [comment]
You could also remove the [code block for the light colours](https://github.com/andreasgrafen/cascade/blob/80e265fc128de9b81a56a7bb0ec4dae7dddc247e/userChrome.css#L81) and remove the [media query](https://github.com/andreasgrafen/cascade/blob/80e265fc128de9b81a56a7bb0ec4dae7dddc247e/userChrome.css#L52) around the dark colours for them to apply globally. c:
Having Firefox think it's in lightmode while actually using dark mode colours *might* cause issues tho. I'd personally just set Firefox to dark mode in the settings to avoid that.

**Comment by wael444** [comment]
> You could also remove the [code block for the light colours](https://github.com/andreasgrafen/cascade/blob/80e265fc128de9b81a56a7bb0ec4dae7dddc247e/userChrome.css#L81) and remove the [media query](https://github.com/andreasgrafen/cascade/blob/80e265fc128de9b81a56a7bb0ec4dae7dddc247e/userChrome.css#L52) around the dark colours for them to apply globally. c:

yeah i didn't know that, sorry

but how do i do it exactly?

**Comment by andreasgrafen** [comment]
> yeah i didn't know that, sorry

Eh, no worries. That's why it's possible to just ask about things. ^—^

If you press `CTRL/CMD + Shift + A` you should end up in the Addons Menu. Here you can go to Themes and select the Dark Theme as default by just enabling it. c:

<img width="221" alt="Themes Menu" src="https://user-images.githubusercontent.com/35840154/172142695-6d0b6cda-083c-4be3-aaca-a62224e86efb.png">

<img width="700" alt="Select Theme" src="https://user-images.githubusercontent.com/35840154/172143730-ca3096c4-ccf1-4a0d-bf64-10b199fc6ce4.png">

**Comment by wael444** [comment]
oh wait sorry, i already knew about that.
to be honest, the only reason i wanted to force colors is to make the cascade CSS smaller.

i was asking on _how_ to just force colors by removing the `@media` thingy you were talking about

**Comment by andreasgrafen** [comment]
Oh, my bad. I misinterpreted the new paragraph then.

You basically just want to delete everything from Line 81 to Line 106, and on Line 52 remove everything before `:root` as well as getting rid of the extra `}` on Line 77.
Now the colour variables are set globally and apply no matter what theme might be selected within firefox itself.

Here is how that would look: [Cascade with only dark colours](https://gist.github.com/andreasgrafen/4db9ebf4fd18b112ca5a415696c0b02f)

**Comment by wael444** [comment]
mfw i did exactly that but did not remove `@media`, thank you.

**Comment by andreasgrafen** [comment]
Happens to the best of us. Most important thing is that it works in the end. You're welcome. c:
