### ISSUE TITLE
search text & icons colours

### ISSUE THREAD

**Issue by wael444** [andreasgrafen/cascade#37]
![image](https://user-images.githubusercontent.com/47404953/173822333-ce0218f4-6b67-45bf-9291-5dc616ad1e29.png)

currently, i expect those  white icons and white text to follow `--inverted-colour` and the grayed out text `--secondary-colour`

**Comment by andreasgrafen** [comment]
Not sure if I fully understand what you mean, but the text and icons should follow the inverted colour setting. If with greyed out text you mean the stuff in the URL – that's done by default in Firefox and is just a transparency effect. There is no custom CSS for this.

**Comment by wael444** [comment]
![image](https://user-images.githubusercontent.com/47404953/173825747-fb58aaab-ca1b-4ffd-9658-9e5a79f7cd5b.png)

**Comment by wael444** [comment]
all that i can get from Firefox Color is
```
{
  "manifest_version": 2,
  "version": "1.0",
  "name": "w",
  "theme": {
    "images": {},
    "properties": {},
    "colors": {
      "toolbar": "rgb(29, 32, 33)",
      "toolbar_text": "rgb(235, 219, 178)",
      "frame": "rgb(29, 32, 33)",
      "tab_background_text": "rgb(235, 219, 178)",
      "toolbar_field": "rgb(29, 32, 33)",
      "toolbar_field_text": "rgb(235, 219, 178)",
      "tab_line": "rgb(235, 219, 178)",
      "popup": "rgb(168, 153, 132)",
      "popup_text": "rgb(235, 219, 178)",
      "tab_loading": "rgb(235, 219, 178)"
    }
  }
}```

i really can't do much with it.

**Comment by andreasgrafen** [comment]
You can repackage that as a standalone colour theme, or you can just use this from the Firefox Color Addon to paint your browser. c:

**Comment by wael444** [comment]
while making my own firefox theme, all it took was this:
```css
#urlbar-input {
  color: #ebdbb2 !important;
} /* holy shit this does it for the accent as well */
```
