### ISSUE TITLE
Ability to hide url bar when unfocused 

### ISSUE THREAD

**Issue by Zabooby** [andreasgrafen/cascade#39]
It would be a great option if there was a way to hide the url bar until a user focuses on it by hovering so tabs get maximum space. 
I know this has been discussed here #20 already but with the theme below I think you could work something out.
[This ](https://github.com/TRPB/FewerFox)theme is sort of what I had in mind. 
Could you perhaps copy over the relevant css code and tweak it to work with cascade (I have no idea how it works)?

**Comment by andreasgrafen** [comment]
Oh, that actually is really interesting! I think this is made possible by using `display: flex;` to align everything in one bar. Back when I started this that resulted in some weird behaviour, but the recent updates to Firefox seem to make this possible.
I'll have a closer look at the animated stuff as an alternative version of Cascade for sure, as well as likely refactoring the whole code in favour of `flex`. ^—^

**Comment by Zabooby** [comment]
It's great to see you are still interested in this feature. I think it will make an already great theme even better! :)

**Comment by andreasgrafen** [comment]
In the meantime I actually got an older edit of the CSS that has *some* of the features – like the buttons sliding on. c:
https://gist.github.com/andreasgrafen/52b0936bfb71cd9973d5516c5fa6b55c

**Comment by Zabooby** [comment]
I'll check it out.

**Comment by Zabooby** [comment]
Any updates?

**Comment by andreasgrafen** [comment]
Sorry for the really late reply, but there actually is an update on this now. The reworked version finally is in a state that makes it close to release. With this there is the ability to set different sizes for the URL Bar based on whether it's focused or not.

![Cascade with unfocused URL Bar](https://user-images.githubusercontent.com/35840154/195950577-cdb08550-7272-4a38-961d-2373c25a30ef.png)
![Cascade with focused URL Bar](https://user-images.githubusercontent.com/35840154/195950589-5f838f79-a746-4330-b4ce-f276dc614cff.png)

**Comment by Zabooby** [comment]
Better late than never, I thought this project had been abandoned. 

Thanks for adding this feature!

**Comment by Zabooby** [comment]
Could [this ](https://github.com/typkrft/FlyerFox) css work? More details [here](https://www.reddit.com/r/FirefoxCSS/comments/ortbxu/f_l_y_e_r_f_o_x/). @andreasgrafen
