### ISSUE TITLE
hide https/state icon 

### ISSUE THREAD

**Issue by wael444** [andreasgrafen/cascade#40]
![image](https://user-images.githubusercontent.com/47404953/177078452-0708e260-ad7d-4af4-87bf-3a7bf3e0ad69.png)
this thing. is it possible to be hidden in this theme? it doesnt really have a point.

**Comment by wael444** [comment]
![image](https://user-images.githubusercontent.com/47404953/177152177-5c01f371-9b88-4608-b9ef-7d5b71ad6993.png)
Thank you ! this is exactly waht i wanted, but the padding is quite too small, is there a way to fix that?

**Comment by Zabooby** [comment]
Yeah I noticed that too, you could try adding flexible space before the url bar in the customise firefox settings. But I found that it had too much padding, I'm sure @andreasgrafen could think of a way to add configurable padding in the userchrome file.
