### ISSUE TITLE
overflow menu overlapped when window is too small

### ISSUE THREAD

**Issue by wael444** [andreasgrafen/cascade#41]
![image](https://user-images.githubusercontent.com/47404953/177170846-a7b30168-a490-4e39-90eb-12ff7841b567.png)

misc:
+ why can't i control the width of the entire oneliner? ive been trying to look for a while and i can't seem to get anywhere. if it is possible it should be added to README.md

**Comment by andreasgrafen** [comment]
You can *enforce* this by setting `#urlbar-container, #urlbar { max-width: var(--uc-urlbar-width) }`. This *doesn't* change anything about the overflow menu. I highly recommend moving addons either to the bookmark toolbar or all the way to the right next to the tabbar.

**Comment by wael444** [comment]
> You can enforce this by setting

i dont see any difference.

> I highly recommend moving addons either to the bookmark toolbar or all the way to the right next to the tabbar.

what do you mean? i have nothing.
![image](https://user-images.githubusercontent.com/47404953/177178440-4f62c3d7-372b-4bc5-b067-04b53d70be9c.png)

**Comment by andreasgrafen** [comment]
> i dont see any difference.

With said rule:
<img width="292" alt="Screen Shot 2022-07-04 at 17 21 44" src="https://user-images.githubusercontent.com/35840154/177183222-b2c95a9d-c8ed-4897-ba9d-8c3e2df660be.png">
And without said rule:
<img width="426" alt="Screen Shot 2022-07-04 at 17 22 34" src="https://user-images.githubusercontent.com/35840154/177183352-261c12f9-6435-4518-b2bd-f0f2ffae5e27.png">

So when you don't have that rule the URL bar will overlay tabs. Isn't that what you mean by controlling the width in the oneliner? Tho, the screenshot you attached is in the small-screen stacked layout. If you want to change the breakpoint to also have the oneline layout below the default width of 1000px check: https://github.com/andreasgrafen/cascade#breakpoint=

--

> what do you mean? i have nothing.

This overflow menu is what I'm talking about. This thing is annoying to work around. So I recommend moving everything out of there.
<img width="54" alt="Screen Shot 2022-07-04 at 17 18 17" src="https://user-images.githubusercontent.com/35840154/177182682-ce0eae11-75f8-4988-a108-afd867ca0cf6.png">

**Comment by wael444** [comment]
i used [navbar_tabs_responsive_oneliner.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/navbar_tabs_responsive_oneliner.css)  as a css firefox theme and the overflow menu stays in place.. how come?

**Comment by andreasgrafen** [comment]
Because it's using a slightly different method to lay things out.

**Comment by wael444** [comment]
> So I recommend moving everything out of there.

about that, it is difficult to actually get it gone.
it still stays there when the window is too small to display the extensions i have despite having nothing in the overflow menu.

is there really nothing that can be done about this issue?

**Comment by andreasgrafen** [comment]
Could you please check out the [rework branch](https://github.com/andreasgrafen/cascade/tree/rework) and let me know if this issue still persists for you? c:

**Comment by wael444** [comment]
![image](https://user-images.githubusercontent.com/47404953/195970570-1706196a-346b-49eb-b90a-fcd0bb74cc68.png)
it happens on default theme, nothing has been changed in the theme's internals.

~~i would also like to point out i use my own theme which is vastly different to cascade, but cascade still looks amazing to me and i might switch back to it later.~~

**Comment by andreasgrafen** [comment]
I really don't get it. Even setting things up exactly how they are on your screenshot – with the reload button and Addons within the URL Bar, even the zoom being at 90%. This just doesn't happen on my end. I have no idea what is going on; sorry. ,—,

<img width="553" alt="Screen Shot 2022-10-15 at 16 25 55" src="https://user-images.githubusercontent.com/35840154/195991675-e9db15aa-e40a-475c-b51e-5bb41b2ac702.png">

**Comment by wael444** [comment]
fresh firefox profile with no changes in css, it still happens.

https://user-images.githubusercontent.com/47404953/195993394-ca6b99ae-d789-4fb9-874d-9d39ebe3498f.mp4

but since it is fixed for you, feel free to close this.

also, may i know which firefox version you are using? i am `Mozilla Firefox 105.0`.

**Comment by andreasgrafen** [comment]
I'm also on the latewst version – so `105.0.3`.
My recommended solution still is to just move all Addons to the Personal Toolbar, but this ofc isn't a proper fix. I'll close this as suggested, but keep this on my personal Todo-List. c:
