### ISSUE TITLE
Status panel covers the "Find in page" and "Quick find" text field

### ISSUE THREAD

**Issue by 2639-unofficial** [andreasgrafen/cascade#42]
For example, press `Ctrl+F` to search for the word "Pull" on the current page, or press `/` to search for the word "Get" on [this page](https://support.mozilla.org/en-US/kb/search-contents-current-page-text-or-links).

Is it possible to raise the status panel when the find bar or the quick find bar is present?

**Comment by andreasgrafen** [comment]
Heya! This should be fixed with [eec990c](https://github.com/andreasgrafen/cascade/commit/eec990c028a298444a8ac1f53700687e95fda081). c:
