### ISSUE TITLE
'More tools' button partly hidden by tabs when 'back' is re-enable

### ISSUE THREAD

**Issue by Gigibeau** [andreasgrafen/cascade#44]
Hey,
as the title states I can't live without the back button and re-enabled it. This causes the more tools button to be partly hidden like in the following picture:

<img width="903" alt="CleanShot 2022-10-13 at 19 24 45@2x" src="https://user-images.githubusercontent.com/65814943/195664595-dce3f6e8-ec28-48c1-91cb-832c2b53108c.png">

Is there an easy fix for this? I messed around with the CSS file but I don't seem to grasp it.

Thanks a lot for this great theme by the way (:!

P.S. I re-enabled the back button by just deleting line 145.

**Comment by andreasgrafen** [comment]
The approach to re-enable the button should be correct. The layout method used in version 2 is a little wonky at times. Could I ask you to check out the [rework branch](https://github.com/andreasgrafen/cascade/tree/rework) and let me know if that issue still persists for you? c:

**Comment by Gigibeau** [comment]
Works perfectly, thank you very much!
