### ISSUE TITLE
White download prompt on MacOS

### ISSUE THREAD

**Issue by ssentanoe** [andreasgrafen/cascade#46]
First of all, thanks for the simple but amazing theme.

**Describe the bug**

The download prompt is completely white for me (screenshot attached).

**Expected behavior**

**Screenshots** (optional)
<img width="380" alt="CleanShot 2022-10-15 at 09 43 17@2x" src="https://user-images.githubusercontent.com/4618600/195975510-3146cbac-9fcf-43ae-a377-d61ed670fa79.png">

**Comment by ssentanoe** [comment]
just realized, that the history window as well.

<img width="1512" alt="CleanShot 2022-10-15 at 13 00 10@2x" src="https://user-images.githubusercontent.com/4618600/195982903-4987467d-8655-47b6-98b9-9255d4b20cec.png">

**Comment by andreasgrafen** [comment]
oh, yeah. That's not good. I'll check on this asap; prob. didn't notice bc I never use these windows. 
Thanks for reporting these. c:

**Comment by andreasgrafen** [comment]
Yeah… I reset the main `window` appearance by accident without redefining it. The commit above should fix this – well, it does on my end. :D
