### ISSUE TITLE
Colours look completely different than screenshot

### ISSUE THREAD

**Issue by WhyNotHugo** [andreasgrafen/cascade#48]
**Describe the bug**

Colours look completely different than screenshot

**Expected behavior**

They should match

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/730811/195999678-a8e19e1d-7cc5-420a-a4bd-f704822887c2.png)

**Comment by andreasgrafen** [comment]
Did you exclude the colour config or are you using an Addon (like Firefox Color) that changes the appearance of Firefox?

**Comment by WhyNotHugo** [comment]
Nope, I excluded nothing.

I don't think I've anything that changes the Firefox appearance, no. Anything specific I should check for?

**Comment by andreasgrafen** [comment]
Hm, okay.. then may I ask which theme you have enabled for Firefox under `about:addons`?

**Comment by WhyNotHugo** [comment]
"System"

**Comment by WhyNotHugo** [comment]
Do colours from the system theme leak on top of the defined CSS colours?

**Comment by andreasgrafen** [comment]
They *should* not. I'm using the system theme myself and I'm not having any issues. Tho, if you could try to set the dark and light theme respectively and see if that makes a difference? CSS is weird sometimes..

**Comment by andreasgrafen** [comment]
Turns our it's not solved by what I've suggested above. Please refer to [this comment](https://github.com/andreasgrafen/cascade/issues/49#issuecomment-1279868189) on #49 to resolve this. In order for this to work properly you'd also want to remove the [colour include](https://github.com/andreasgrafen/cascade/blob/504215d1e245cbd135e866e0cb12e0c8e06a0805/chrome/userChrome.css#L32) from the main file.
