### ISSUE TITLE
re- enabling windows controls 

### ISSUE THREAD

**Issue by THIAXX** [andreasgrafen/cascade#50]
how i can return the windows controls?

**Comment by andreasgrafen** [comment]
Cascade offers an [alternative config file](https://github.com/andreasgrafen/cascade/blob/main/chrome/includes/cascade-config-mouse.css) that reintroduces some of the UI elements that are necessary to use Firefox with a mouse. To use these settings simply substitue the [regular config include](https://github.com/andreasgrafen/cascade/blob/main/chrome/userChrome.css#L31) with the one for mouse support.

```diff
- @import 'includes/cascade-config.css';
+ @import 'includes/cascade-config-mouse.css';
@import 'includes/cascade-colours.css';
```

This config brings back:

- Navigation Buttons
- the URL Bar Bookmark Button
- the Hamburger Menu
- Tab Close Buttons (on hover)

ref: https://github.com/andreasgrafen/cascade#mouse-support
