### ISSUE TITLE
Light mode selections from the URL bar aren't discernable. 

### ISSUE THREAD

**Issue by waynehoover** [andreasgrafen/cascade#51]
First of all, thanks for this great theme!

**Describe the bug**
When in light mode, when I hit cmd-l to focus the URL quick switch bar and then use the up and down arrow keys it's not clear which item I am selecting (to go to when I hit return), sometimes the color of the text changes on the selected item, but that's only in the firefox suggest area. 

The only way I know which item I'm currently selected on is that text to the right appears "Search with Google" as shown in the screenshot.

The background should darken around the currently selected item in this dropdown.

**Screenshots** (optional)
<img width="483" alt="image" src="https://user-images.githubusercontent.com/115143/196786244-715ec33d-989e-42da-b557-08fda7befdd6.png">

**Comment by andreasgrafen** [comment]
Oh, my bad! I messed up with the variables, so this is actually affecting **all** colour schemes. Luckily it's easy to fix. Thanks for letting me know! c:
