### ISSUE TITLE
How to move overflow menu

### ISSUE THREAD

**Issue by 0rphee** [andreasgrafen/cascade#52]
It seems that by default, the overflow menu stays on the right side of the search bar, and left to the tabs, but I want to move it all the way to the right. How can I do this? Firefox doesn't let me grab it as if it was another toolbar item... 

Sorry if this has been answered before and I haven't seen it yet.

Firefox 106.0
MacOS 12.6

Thank you in advance!

<img width="1431" alt="Screen Shot 2022-10-19 at 9 51 52 p m" src="https://user-images.githubusercontent.com/79347623/196845038-e3c83656-8e38-4242-ad57-43414031c522.png">

**Comment by andreasgrafen** [comment]
> Is there a hotkey to toggle the side view?

Sadly not, no. I'm kinda frustrated by that as well. There might be a way to set custom hotkeys via an Addon, but I haven't looked into that idea further.

**Comment by 0rphee** [comment]
Oh what shame! Thank you very much though.

**Comment by andreasgrafen** [comment]
I really is … yeah. I still hope that some day we'll be allowed to move it — we can move *everything else*, so why is the overflow menu stuck there? :c
