### ISSUE TITLE
Side view doesn't close when I click the "X" button

### ISSUE THREAD

**Issue by EasterEggo** [andreasgrafen/cascade#58]
**Describe the bug**
When I click in the "X" button in the Side view panel, it will freeze the resizing functionality and the view doesn't actually close.

edit: i forgot to mention that this behavior doesn't happen when I remove the `@import 'integrations/side-view/cascade-sideview.css';
` line.

**Expected behavior**
When I click in the button, the side view gets closed

**Comment by andreasgrafen** [comment]
Seems like this broke with one of the latest Firefox updates.. Reversing the flex order (making the button appear at the top) seems to fix the issue. Doesn't look as nice, but it works! c:
