### ISSUE TITLE
Button link preview is in incorrect position

### ISSUE THREAD

**Issue by ssssamstrup** [andreasgrafen/cascade#65]
**Describe the bug**
«Hover link preview» isn't where expected.

**Expected behavior**
That the link is shown in the bottom left corner, without padding/margin.

**Screenshots** (optional)
![Screenshot 2022-11-29 at 06 20 06](https://user-images.githubusercontent.com/4302516/204445906-b1f8250b-539e-4473-b9c5-c8eac2e9a344.png)

**Comment by ssssamstrup** [comment]
Apart from this: thank you for such a great «extention» for Firefox! Would be great if it could become a real extension one day, for more people to enjoy. :)

**Comment by andreasgrafen** [comment]
I'm glad you like it! The floating panel is actually intentional, but you can simply remove this feature by excluding it's [include within the main CSS file](https://github.com/andreasgrafen/cascade/blob/78ba95b83ef74b0080464540929bc5e724279ee4/chrome/userChrome.css#L36). c:
