### ISSUE TITLE
In the `README` installation section, add the restart step.

### ISSUE THREAD

**Issue by ismael-lajaaiti** [andreasgrafen/cascade#67]
Between point [4. and 5. in the README](https://github.com/andreasgrafen/cascade/blob/467c8df6a83b877e613b28ec3ae8a47c25784483/README.md?plain=1#L59), you could add a step on how to restart firefox properly so the theme is updated, something like:
_Restart firefox by going to 'about:profiles' and click 'Restart normally'. The theme should now be updated._

I'm making this suggestion because after step 4. I tried naively to restart firefox (with cmd Q, then re-open it) to update the theme, but it didn't work. I had to google an other theme installation to find the 'right way' to restart firefox. 

Hope you find this suggestion useful, and thanks for providing this awesome theme.

**Comment by andreasgrafen** [comment]
> (with cmd Q, then re-open it)

Wait.. I do it like this all the time, and it works perfectly fine. CMD + Q should completely quit the process, no? At least it does for me. Tho I guess it doesn't harm to mention it on the README in case someone else runs into a similar issue.
Thanks for bringing this up. c:
