### ISSUE TITLE
Pinned tabs in sidebar stack (?) horizontally

### ISSUE THREAD

**Issue by Thesecondbestname** [andreasgrafen/cascade#68]
When using the sidebar and pinning tabs they are offset and allign horizontally instead of vertically.

Either the tabs stack horizontally or multiple only show when the sidebar is expanded.

![Screenshot from 2023-01-09 16-34-43](https://user-images.githubusercontent.com/111275274/211346250-714723f3-da52-49ea-a4c7-eb75fd73f83f.png)

I am a newbie and as such I wasn't quite sure where or how I could offset pinned tabs. Please be gentle!

**Comment by Bastigonzales** [comment]
Go to your add ons settings and look for **Tab Center Reborn** try change the settings to "Dynamic" or "Enabled" and try to uncheck "Favicon-only Pinned Tabs" see what the result looks like.

![firefox_GKemxWJnxu](https://user-images.githubusercontent.com/42995601/214331574-1b608c27-181f-4764-8f42-21c0925eb0a4.png)

**Comment by Thesecondbestname** [comment]
Thanks a Lot! I can live without the seperator line. Only real place to say this but I really enjoy your work!
