### ISSUE TITLE
Should the new tab page be set to a matching color?

### ISSUE THREAD

**Issue by hotsno** [andreasgrafen/cascade#71]
In the README screenshots, the color of the new tab page perfectly matches the colors of the rest of the theme. I'm wondering if there's anything special I'm supposed to do to get this. For me, it's a different color. I tried installing the Firefox Color theme in the README as well.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/71658949/216157552-23ed8371-1627-4d03-81b6-2dd33734dc1c.png">

**Comment by andreasgrafen** [comment]
Oh, uhm.. the newtab page on the Screenshots is actually custom. That's why it's so seemless. If you don't want to set a custom page as your newtab page you could also change the `background_color` settings in `about:config` tho. c:

**Comment by hotsno** [comment]
Thanks! Changing `browser.display.background_color.dark` worked.
