### ISSUE TITLE
Tabs vertically centered

### ISSUE THREAD

**Issue by karamanliev** [andreasgrafen/cascade#80]
**Describe the bug**
I adore the theme and I'm using it in combination with catppuccin, but for some reason the tabs and some of the buttons are not vertically centered in the navbar. I tried changing stuff like ``--tab-min-height``, add some paddings and margins and so on, but nothing seems to help and something is always off in the end.

They are off by few pixels and in reality it's not a big deal, but for some reason it's driving me crazy. Do you have any suggestions how to fix it?

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/22788016/230861879-b759cd01-0b6b-4c8a-92d6-7e98ce97498b.png)

**Comment by karamanliev** [comment]
So I created a new profile and cloned the repo to check it out and that was the moment that I realized something. The theme is fine, even with my custom config.

I use [FancyZones](https://github.com/microsoft/PowerToys) and I like my apps not fully maximized, but the OS creates 1px grayish border around every window that is not fullscreen and that's why everything looks off 😄 I measured it again and everything is perfect when I take that 1px into account.

Thank you for the support and for the awesome theme and sorry for the issue, you may close it.

**Comment by andreasgrafen** [comment]
Ah, okay. I honestly wouldn't have wondered if this is another thing to add to the long list of things that behave differently on different setups. But I'm relieved that it's not. :D

No worries – I'd always rather want people to open issues and get them resolved, than people with issues being to afraid to ask. The goal is to have a solution in the end. And this can always be a reference for people experiencing similar issues. ^—^
