### ISSUE TITLE
any way to get adaptive tab bar colour to work with tab center reborn ?

### ISSUE THREAD

**Issue by kaem-e** [andreasgrafen/cascade#86]
i noticed the readme mentioned excluding the colours include to get the Adaptive Tab Bar Color extension working with firefox & cascade. i was wondering if there was a way to have the background colour of tab center reborn also adapt to this colour ?

![image](https://github.com/andreasgrafen/cascade/assets/46230985/78677951-bf00-4f50-9c3a-a7eddac3c5aa)

**Comment by T0kyoB0y** [comment]
Hi, yes, actually you can change the color of the sidebar depending of the titlebar, you can do it adding to the sidebar Custom Stylesheet:
![image](https://github.com/andreasgrafen/cascade/assets/119447307/abaafd84-65f8-41e3-b56d-d23e108af210)
