### ISSUE TITLE
Firefox 113.0 Update Breaks CSS

### ISSUE THREAD

**Issue by steveharsant** [andreasgrafen/cascade#87]
**Describe the bug**
The 113.0 update of Firefox released on the 9th May 2023, breaks Cascade's styling so that the address bar sits above the tab bar, if  the bookmarks bar is visible it sits above the address bar, and the zoom level indicator shows when it is set to be hidden, and 

**Expected behavior**
Address bar should be on the same row as the tabs bar with the address bar on the left

**Screenshots** (optional)
![image](https://github.com/andreasgrafen/cascade/assets/38461965/09ad4579-e85c-4a0c-aa88-b4be6f524f48)

![image](https://github.com/andreasgrafen/cascade/assets/38461965/a83d8daf-242b-4568-abc2-e30fd4177d04)

**Comment by Manix80** [comment]
same problem here. is there a manipulation to do? or a patch planned?

**Comment by Manix80** [comment]
> @Manix80 this commit resolved the issues for me https://github.com/karamanliev/cascade/commit/9403343b9fb055767e32b7deb5c9a9c3c078b76e

thank you works perfectly!
simple question, why is it so long to integrate in the repository?

**Comment by waynehuang3440** [comment]
the [fix](https://github.com/karamanliev/cascade/commit/9403343b9fb055767e32b7deb5c9a9c3c078b76e) only works on maximized window for me.

<img width="960" alt="image" src="https://github.com/andreasgrafen/cascade/assets/72854267/b58b811c-8bfc-4627-94ba-fe4243cca5f2">

<img width="735" alt="image" src="https://github.com/andreasgrafen/cascade/assets/72854267/dddf3d72-bd6d-40d0-b17b-96c006bee1a7">

**Comment by andreasgrafen** [comment]
> simple question, why is it so long to integrate in the repository?

Oh.. well. Simply because I've been inactive for quite some time due to personal reasons. And since I'm currently the only maintainer nothing happened with Cascade over the past couple months. :/
