### ISSUE TITLE
[Bug] Addons Installation/Remove, and Firefox Update Notification Stuck

### ISSUE THREAD

**Issue by benyaminl** [andreasgrafen/cascade#9]
Hello, I'm facing addons installation notification stuck, can't be closed and sometimes blinked, is there any CSS rule to hide the notification permanently, and I need to restart the browser to make the notification disappear. This also applied to other notification that rely on hamburger menu. The hamburger menu already disappear but this problem still occur, I remember it's mentioned on the readme, but now seems it's not mentioned any-more after several update. 

Any pointer is appreciated. Thank you.

**Comment by andreasgrafen** [comment]
I've been trying to find away around this issue, but I can't really find a solution that's working well.. It's really annoying that this stupid button and the popup are tied together like this..
Right now my local solution is to set this rule instead of hiding the button: `#PanelUI-menu-button { list-style-image: none !important; }` This seems to work for the most part. But i don't really like the solution either beause it's just visually hiding the button but it's still there and working.. by far not perfect.

**Comment by benyaminl** [comment]
> 
> 
> Hey there, thanks for reaching out! c: I've been trying to find away around this issue, but I can't really find a solution that's working well.. It's really annoying that this stupid button and the popup are tied together like this.. Right now my local solution is to set this rule instead of hiding the button: `#PanelUI-menu-button { list-style-image: none !important; }` This seems to work for the most part. But i don't really like the solution either beause it's just visually hiding the button but it's still there and working.. by far not perfect.

Hello, I tried another approach and it seems to work, could you also tried this by adding this code to your userChrome.css

```css
#PanelUI-menu-button { 
    list-style-image: none !important;
    padding: 0px !important;
}
#PanelUI-menu-button .toolbarbutton-icon {
    width: 1px !important;
}
#PanelUI-menu-button .toolbarbutton-badge-stack {
    padding: 0px !important;
}
```

I tried to make the button only have 1px of width, and test it by installing extension, and resizing window, etc, the notification still there and doesn't show or hide randomly like before. I tried this on Nightly 96.01a and 94.0 (not 94.0.2). If this also works on your part, than we can assume as long as the menu button is there even only 1 pixel, the notification pop up will works.

**Comment by benyaminl** [comment]
@andreasgrafen anyway, do I need to ppen pull request or will you integrate this solution to the cas in next release? 😂

**Comment by andreasgrafen** [comment]
I mean, I wouldn't mind a pull request as it would also credit you for fixing this, but I can just add it myself and push it. I dont mind either way – so, however you prefer. ^—^
